[package]
name = "fibonacci"
version = "0.1.0"
edition = "2021"
authors = ["gdim47 gdim47@protonmail.com"]

[[bin]]
name = "fibonacci"
path = "src/main.rs"

[lib]
name = "fib"
path = "src/lib.rs"

[dependencies]
